# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 249f6313f1b5fd4b6752e8fea23cac23a921f424704356fd4ee2d37f27139a15b0ec656a1398ab42bb0130767f1f204c4c8d3f5db89eb000b7586e047ef69c48

test:
  secret_key_base: 05282273576ed661b601e5e5fabce89dc1f1fdccc7a55f8679b845bdc3468f37c1375fd2546d386e22138901602c3d93c54591bf2b919169e66d90517822420b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
